TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += tjmpap.db
DATA += tjmpap.proto

#=======================================
include $(TOP)/configure/RULES
